name = "typingmind-chatbot"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "0460574641fdbb98159c98ebf593e2bd"

[assets]
directory = "./assets"

[vars]
TYPINGMIND_API_HOST = "https://api.typingmind.com"

# Secrets should be set via Cloudflare dashboard or wrangler secret command:
# wrangler secret put ADMIN_PASSWORD
# wrangler secret put DEFAULT_API_KEY

[env.production]
[env.production.vars]
TYPINGMIND_API_HOST = "https://api.typingmind.com"

[[kv_namespaces]]
binding = "AGENT_CONFIG"
id = "93300b53059246969bfc4e85f97e3adc"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "c65661c3a010484fa0bc360cd4f98be1"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "8d28f73263ac4fefb9e89016086fa26a"

[[kv_namespaces]]
binding = "ADMIN_SESSIONS"
id = "da66ec6fbda04790b24c30791c8b48ac"

[[d1_databases]]
binding = "DB"
database_name = "typingmind-chatbot-db"
database_id = "48c95c1c-4f72-4195-928b-eaaaa2746106"

# Development overrides
[env.development]
[env.development.vars]
TYPINGMIND_API_HOST = "https://api.typingmind.com"
# For local development, create .dev.vars file with:
# ADMIN_PASSWORD = "your-dev-password"
# DEFAULT_API_KEY = "your-dev-api-key"